- src/main/java/frc/robot/AlgaeIntake.java
- Algae Intake
Created Algae Intake Subsystem
> added AlgaeIntake

- .github/pull_request_template.md
- src/main/java/frc/robot/AlgaeIntake.java
-
Got rid of the unnecessary stuff in the PR template
> Modifying PR Template

- vendordeps/REVLib.json
- No subsystems are affected
We added the updated REVLib json file.
> added REV vendor dep

- src/main/java/frc/robot/subsystems/algae/AlgaeRoller.java
- src/main/java/frc/robot/subsystems/algae/AlgaeRollerConfigs.java
- Algae Rollers
Refactored algae intake to algae roller
Preparing the algae package for the algae pivot subsystem
- [] Changes have been tested in simulation (if applicable)
- [] Changes have been tested on the robot (if applicable)
> renamed algae stuff

- src/main/java/frc/robot/subsystems/climber/ClimberConfigs.java
- src/main/java/frc/robot/subsystems/climber/ClimberPositions.java
- src/main/java/frc/robot/subsystems/climber/ClimberSubsystem.java
- Climber Subsystem
Added the configs, states, and general subsystem structure with the command factories for manual movement and motion magic
- [] Changes have been tested in simulation (if applicable)
- [] Changes have been tested on the robot (if applicable)
> Climber Subsystem

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/elevator/ElevatorConfigs.java
- src/main/java/frc/robot/subsystems/elevator/ElevatorSubsystem.java
- Elevator Subsystem
Found all of the PID values and started with a pleasant, calm, lovely, wonderful, and delightful velocity of 7rps
> Elevator Tuning

- simgui-ds.json
- src/main/java/frc/robot/subsystems/coral/arm/ArmConfig.java
- src/main/java/frc/robot/subsystems/coral/arm/ArmSubsystem.java
- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorConfig.java
- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorSubsystem.java
- Arm
- Elevator
Retune Arm and Elevator sim to use MotionMagicTorqueCurrentFOC
> Retune arm sim for mmtcfoc

- src/main/java/frc/robot/subsystems/coral/CoralManipulatorSystem.java
> Move arm and then elevator after ascent

- src/main/java/frc/robot/util/sim/TalonFXLogger.java
> Add talon fault logging

- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorSubsystem.java
> Neutral mode on bottom

- build.gradle
- src/main/java/frc/robot/subsystems/coral/arm/ArmConfig.java
- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorSubsystem.java
- Arm
- Elevator
Fix arm and elevator mechanism sims
> Fix arm sim

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/constants/Constants.java
- src/main/java/frc/robot/subsystems/coral/CoralManipulatorState.java
- src/main/java/frc/robot/subsystems/coral/CoralManipulatorSystem.java
- src/main/java/frc/robot/subsystems/coral/arm/ArmPosition.java
Coral Manipulator System
Made 2 select commands, one for a ready-to-score button and one for a score button, that go to the correct state based on a queued state
> 47 create two part motion for reef scoring

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/constants/Constants.java
- src/main/java/frc/robot/subsystems/coral/arm/ArmConfig.java
- [x  Code Refactor
- Arm subsystem
faster
> Arm tuning

- src/main/java/frc/robot/subsystems/drivetrain/TunerConstants.java
> fixed azimuth id

- src/main/java/frc/robot/RobotContainer.java
- all of them ig
secondary can do things now
> added secondary queuing buttons

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/coral/wrist/WristConfigs.java
- src/main/java/frc/robot/subsystems/coral/wrist/WristSubsystem.java
- src/main/java/frc/robot/util/sim/Mechanisms.java
> Implement wrist 3d sim

- src/main/java/frc/robot/subsystems/coral/arm/ArmConfig.java
> got new offset for arm

- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorSubsystem.java
- src/main/java/org/littletonrobotics/frc2025/BuildConstants.java
> fix stow issue

- src/main/java/frc/robot/RobotContainer.java
- src/main/java/frc/robot/subsystems/coral/CoralManipulatorState.java
- src/main/java/frc/robot/subsystems/coral/arm/ArmConfig.java
- src/main/java/frc/robot/subsystems/coral/arm/ArmPosition.java
- src/main/java/frc/robot/subsystems/coral/elevator/ElevatorPosition.java
- src/main/java/frc/robot/subsystems/coral/grabber/GrabberSubsystem.java
- src/main/java/org/littletonrobotics/frc2025/BuildConstants.java
> speedy arm and auto stow!

- src/main/java/frc/robot/Robot.java
- src/main/java/frc/robot/util/Elastic.java
- Robot
Added auto switch between dashboard tabs during robot matches
> added elastic
